encoding: utf-8

# SEO related info
title: Zhuoyi Huang Blog
description: 黄卓仪的个人博客
keywords: Zhuoyi Huang,Blog,Research notes,Programming notes
author: Zhuoyi Huang
# footerText: 'Copyright © 2016 皖ICP备16016174号'

# don't edit
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://blog.tmaize.net'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/86335

# 菜单
menu:
  - title: About
    url: /pages/about.html
  - title: Blogs
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: OtherLinks
    url: /pages/links.html
  

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: true

# 友情链接
links:
  - title: Linkedin_ZhuoyiHuang
    url: https://www.linkedin.com/in/zhuoyi-huang-0a8229168/
